const data = {
    products: [
      {
        _id: '1',
        name: 'Spring Shirt',
        category: 'Shirts',
        image: '/images/p1.png',
        price: 120,
        countInStock: 10,
        color: 'white',
        size: 'XL',
        rating: 1,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Summer Shirt',
        category: 'Shirts',
        image: '/images/p2.png',
        price: 100,
        countInStock: 20,
        color: 'black',
        size: 'L',
        rating: 2.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Kitty Dress',
        category: 'Dresses',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        color: 'red',
        size: 'L',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Loli Dress',
        category: 'Dresses',
        image: '/images/p4.jpg',
        price: 678,
        countInStock: 15,
        color: 'yellow',
        size: 'M',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Cindrella Dress',
        category: 'Dresses',
        image: '/images/p5.jpg',
        price: 365,
        countInStock: 0,
        color: 'black',
        size: 'M',
        rating: 3,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Dian Dress',
        category: 'Dresses',
        image: '/images/p6.jpg',
        price: 539,
        countInStock: 12,
        color: 'orange',
        size: 'XXL',
        rating: 5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;